### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by SolitudeSF** [Nimaoth/Nev#22]
Building latest commit with nim 2.0.6 fails with

```
In file included from /home/solitude/git/app/Nev/nimbledeps/pkgs2/nimwasmtime-0.1.7-54d6dba8f74ac561053551462447a7498bec84ef/wasmtime/crates/c-api/include/wasmtime.h:182,
                 from /home/solitude/git/app/Nev/nimbledeps/pkgs2/treesitter-0.1.15-3bb5409058f8c1b2c651c990880370bdf0ef7b24/treesitter/lib/src/./wasm_store.c:17,
                 from /home/solitude/git/app/Nev/nimbledeps/pkgs2/treesitter-0.1.15-3bb5409058f8c1b2c651c990880370bdf0ef7b24/treesitter/lib/src/lib.c:14:
/home/solitude/git/app/Nev/nimbledeps/pkgs2/nimwasmtime-0.1.7-54d6dba8f74ac561053551462447a7498bec84ef/wasmtime/crates/c-api/include/wasi.h:12:10: fatal error: wasmtime/conf.h: No such file or directory
   12 | #include <wasmtime/conf.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by Nimaoth** [comment]
Which command did you use to compile? And can were there any errors with building wasmtime before this error?
Try compiling with `nimble buildDesktop -d:appBuildWasmtime --forceBuild`.

**Comment by Nimaoth** [comment]
You should see this `Configure and build wasmtime, this might take a while...` in the build logs and after that a successfull wasmtime build. You need cargo for that aswel

**Comment by SolitudeSF** [comment]
`nimble buildDesktop -d:appBuildWasmtime --forceBuild` worked. i tried building with plain `nimble build` and wasmtime wasnt building then.
